apiVersion: apps/v1
kind: Deployment
metadata:
  name: orange
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orange
  template:
    metadata:
      labels:
        app: orange
    spec:
      containers:
      - name: orange
        image: ucheor/argocd-trf-k8s-demo-orange:v1
        ports:
        - containerPort: 80
