apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../base/blue

# Adds a prefix or namespace specific to Cluster-A
namespace: dev-blue
namePrefix: dev-

# Built-in image tag management
images:
  - name: argocd-trf-k8s-demo-blue
    newName: ucheor/argocd-trf-k8s-demo-blue
    newTag: v1

replicas:
  - name: blue  # Make sure this matches the metadata.name of the deployment in your base folder
    count: 1

patches:
  - target:
      kind: Service
      name: dev-blue-svc
    patch: |-
      - op: replace
        path: /spec/ports/0/port
        value: 8081
      - op: replace
        path: /spec/type
        value: LoadBalancer